### ISSUE TITLE
Questions regarding the operation of SINr compared to others 

### ISSUE THREAD

**Issue by BradKML** [anthonimes/SINr#1]
As noted in https://github.com/CompNet/Orleans/issues/1 there are some weird questions.
1. Why can SINr work with all the algorithms included in [CDLib](http://cdlib.readthedocs.io/)?
2. How are SINr's vectors different from the ones from [KarateClub](https://karateclub.readthedocs.io/)?
3. How does SINr's clustering work compared to [Scikit-Learn](https://scikit-learn.org/stable/modules/clustering.html)?
4. How is SINr different from [RoleSim](https://github.com/abhishekmaha23/RoleSim-Python) and [RolX](https://github.com/dkaslovsky/GraphRole) and [RMST-RBS](https://github.com/barahona-research-group/RMST) ?

**Comment by nicolasdugue** [comment]
Hi Brandon,

Please, read the papers I recommended to you :
SINr and how it relates to the KarateClub : https://hal.archives-ouvertes.fr/hal-03197434
Community Roles and Centrality : https://www.researchgate.net/publication/329426018_Bringing_a_Feature_Selection_Metric_from_Machine_Learning_to_Complex_Networks_Volume_2_Proceedings_The_7th_International_Conference_on_Complex_Networks_and_Their_Applications_COMPLEX_NETWORKS_2018
The answers to your questions are in these papers, especially the first one.

**Comment by BradKML** [comment]
@nicolasdugue the first one has been read, looks awesome yet simple.
For the centrality vs roles part, I don't think RolX is purely centrality-based but rather node feature based. for RoleSim it attempts to use structural similarity ranking to form a CD-workable graph, so the opposite of vectorization => clustering.
